// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: runtime/v1/topology.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ServiceType indicates whether a service provides, consumes, or does both.
type ServiceType int32

const (
	ServiceType_SERVICE_TYPE_UNSPECIFIED ServiceType = 0
	ServiceType_SERVICE_TYPE_SERVER      ServiceType = 1
	ServiceType_SERVICE_TYPE_CLIENT      ServiceType = 2
	ServiceType_SERVICE_TYPE_HYBRID      ServiceType = 3
)

// Enum value maps for ServiceType.
var (
	ServiceType_name = map[int32]string{
		0: "SERVICE_TYPE_UNSPECIFIED",
		1: "SERVICE_TYPE_SERVER",
		2: "SERVICE_TYPE_CLIENT",
		3: "SERVICE_TYPE_HYBRID",
	}
	ServiceType_value = map[string]int32{
		"SERVICE_TYPE_UNSPECIFIED": 0,
		"SERVICE_TYPE_SERVER":      1,
		"SERVICE_TYPE_CLIENT":      2,
		"SERVICE_TYPE_HYBRID":      3,
	}
)

func (x ServiceType) Enum() *ServiceType {
	p := new(ServiceType)
	*p = x
	return p
}

func (x ServiceType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ServiceType) Descriptor() protoreflect.EnumDescriptor {
	return file_runtime_v1_topology_proto_enumTypes[0].Descriptor()
}

func (ServiceType) Type() protoreflect.EnumType {
	return &file_runtime_v1_topology_proto_enumTypes[0]
}

func (x ServiceType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ServiceType.Descriptor instead.
func (ServiceType) EnumDescriptor() ([]byte, []int) {
	return file_runtime_v1_topology_proto_rawDescGZIP(), []int{0}
}

// ServiceLanguage describes the implementation language.
type ServiceLanguage int32

const (
	ServiceLanguage_SERVICE_LANGUAGE_UNSPECIFIED ServiceLanguage = 0
	ServiceLanguage_SERVICE_LANGUAGE_TYPESCRIPT  ServiceLanguage = 1
	ServiceLanguage_SERVICE_LANGUAGE_RUST        ServiceLanguage = 2
	ServiceLanguage_SERVICE_LANGUAGE_CPP         ServiceLanguage = 3
	ServiceLanguage_SERVICE_LANGUAGE_GO          ServiceLanguage = 4
	ServiceLanguage_SERVICE_LANGUAGE_PYTHON      ServiceLanguage = 5
	ServiceLanguage_SERVICE_LANGUAGE_JAVA        ServiceLanguage = 6
	ServiceLanguage_SERVICE_LANGUAGE_CSHARP      ServiceLanguage = 7
)

// Enum value maps for ServiceLanguage.
var (
	ServiceLanguage_name = map[int32]string{
		0: "SERVICE_LANGUAGE_UNSPECIFIED",
		1: "SERVICE_LANGUAGE_TYPESCRIPT",
		2: "SERVICE_LANGUAGE_RUST",
		3: "SERVICE_LANGUAGE_CPP",
		4: "SERVICE_LANGUAGE_GO",
		5: "SERVICE_LANGUAGE_PYTHON",
		6: "SERVICE_LANGUAGE_JAVA",
		7: "SERVICE_LANGUAGE_CSHARP",
	}
	ServiceLanguage_value = map[string]int32{
		"SERVICE_LANGUAGE_UNSPECIFIED": 0,
		"SERVICE_LANGUAGE_TYPESCRIPT":  1,
		"SERVICE_LANGUAGE_RUST":        2,
		"SERVICE_LANGUAGE_CPP":         3,
		"SERVICE_LANGUAGE_GO":          4,
		"SERVICE_LANGUAGE_PYTHON":      5,
		"SERVICE_LANGUAGE_JAVA":        6,
		"SERVICE_LANGUAGE_CSHARP":      7,
	}
)

func (x ServiceLanguage) Enum() *ServiceLanguage {
	p := new(ServiceLanguage)
	*p = x
	return p
}

func (x ServiceLanguage) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ServiceLanguage) Descriptor() protoreflect.EnumDescriptor {
	return file_runtime_v1_topology_proto_enumTypes[1].Descriptor()
}

func (ServiceLanguage) Type() protoreflect.EnumType {
	return &file_runtime_v1_topology_proto_enumTypes[1]
}

func (x ServiceLanguage) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ServiceLanguage.Descriptor instead.
func (ServiceLanguage) EnumDescriptor() ([]byte, []int) {
	return file_runtime_v1_topology_proto_rawDescGZIP(), []int{1}
}

// HealthState represents the health status of a service.
type HealthState int32

const (
	HealthState_HEALTH_STATE_UNKNOWN   HealthState = 0
	HealthState_HEALTH_STATE_STARTING  HealthState = 1
	HealthState_HEALTH_STATE_HEALTHY   HealthState = 2
	HealthState_HEALTH_STATE_DEGRADED  HealthState = 3
	HealthState_HEALTH_STATE_UNHEALTHY HealthState = 4
)

// Enum value maps for HealthState.
var (
	HealthState_name = map[int32]string{
		0: "HEALTH_STATE_UNKNOWN",
		1: "HEALTH_STATE_STARTING",
		2: "HEALTH_STATE_HEALTHY",
		3: "HEALTH_STATE_DEGRADED",
		4: "HEALTH_STATE_UNHEALTHY",
	}
	HealthState_value = map[string]int32{
		"HEALTH_STATE_UNKNOWN":   0,
		"HEALTH_STATE_STARTING":  1,
		"HEALTH_STATE_HEALTHY":   2,
		"HEALTH_STATE_DEGRADED":  3,
		"HEALTH_STATE_UNHEALTHY": 4,
	}
)

func (x HealthState) Enum() *HealthState {
	p := new(HealthState)
	*p = x
	return p
}

func (x HealthState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HealthState) Descriptor() protoreflect.EnumDescriptor {
	return file_runtime_v1_topology_proto_enumTypes[2].Descriptor()
}

func (HealthState) Type() protoreflect.EnumType {
	return &file_runtime_v1_topology_proto_enumTypes[2]
}

func (x HealthState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HealthState.Descriptor instead.
func (HealthState) EnumDescriptor() ([]byte, []int) {
	return file_runtime_v1_topology_proto_rawDescGZIP(), []int{2}
}

// ServiceState represents the lifecycle state of a service node.
type ServiceState int32

const (
	ServiceState_SERVICE_STATE_UNSPECIFIED ServiceState = 0
	ServiceState_SERVICE_STATE_REGISTERED  ServiceState = 1
	ServiceState_SERVICE_STATE_IDLE        ServiceState = 2
	ServiceState_SERVICE_STATE_ACTIVE      ServiceState = 3
	ServiceState_SERVICE_STATE_STALE       ServiceState = 4
	ServiceState_SERVICE_STATE_DEAD        ServiceState = 5
)

// Enum value maps for ServiceState.
var (
	ServiceState_name = map[int32]string{
		0: "SERVICE_STATE_UNSPECIFIED",
		1: "SERVICE_STATE_REGISTERED",
		2: "SERVICE_STATE_IDLE",
		3: "SERVICE_STATE_ACTIVE",
		4: "SERVICE_STATE_STALE",
		5: "SERVICE_STATE_DEAD",
	}
	ServiceState_value = map[string]int32{
		"SERVICE_STATE_UNSPECIFIED": 0,
		"SERVICE_STATE_REGISTERED":  1,
		"SERVICE_STATE_IDLE":        2,
		"SERVICE_STATE_ACTIVE":      3,
		"SERVICE_STATE_STALE":       4,
		"SERVICE_STATE_DEAD":        5,
	}
)

func (x ServiceState) Enum() *ServiceState {
	p := new(ServiceState)
	*p = x
	return p
}

func (x ServiceState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ServiceState) Descriptor() protoreflect.EnumDescriptor {
	return file_runtime_v1_topology_proto_enumTypes[3].Descriptor()
}

func (ServiceState) Type() protoreflect.EnumType {
	return &file_runtime_v1_topology_proto_enumTypes[3]
}

func (x ServiceState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ServiceState.Descriptor instead.
func (ServiceState) EnumDescriptor() ([]byte, []int) {
	return file_runtime_v1_topology_proto_rawDescGZIP(), []int{3}
}

// ConnectionState represents the lifecycle state of an edge.
type ConnectionState int32

const (
	ConnectionState_CONNECTION_STATE_UNSPECIFIED ConnectionState = 0
	ConnectionState_CONNECTION_STATE_IDLE        ConnectionState = 1
	ConnectionState_CONNECTION_STATE_ACTIVE      ConnectionState = 2
	ConnectionState_CONNECTION_STATE_FAILED      ConnectionState = 3
)

// Enum value maps for ConnectionState.
var (
	ConnectionState_name = map[int32]string{
		0: "CONNECTION_STATE_UNSPECIFIED",
		1: "CONNECTION_STATE_IDLE",
		2: "CONNECTION_STATE_ACTIVE",
		3: "CONNECTION_STATE_FAILED",
	}
	ConnectionState_value = map[string]int32{
		"CONNECTION_STATE_UNSPECIFIED": 0,
		"CONNECTION_STATE_IDLE":        1,
		"CONNECTION_STATE_ACTIVE":      2,
		"CONNECTION_STATE_FAILED":      3,
	}
)

func (x ConnectionState) Enum() *ConnectionState {
	p := new(ConnectionState)
	*p = x
	return p
}

func (x ConnectionState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ConnectionState) Descriptor() protoreflect.EnumDescriptor {
	return file_runtime_v1_topology_proto_enumTypes[4].Descriptor()
}

func (ConnectionState) Type() protoreflect.EnumType {
	return &file_runtime_v1_topology_proto_enumTypes[4]
}

func (x ConnectionState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ConnectionState.Descriptor instead.
func (ConnectionState) EnumDescriptor() ([]byte, []int) {
	return file_runtime_v1_topology_proto_rawDescGZIP(), []int{4}
}

// UpdateType indicates what kind of topology change occurred.
type UpdateType int32

const (
	UpdateType_UPDATE_TYPE_UNSPECIFIED  UpdateType = 0
	UpdateType_UPDATE_TYPE_SNAPSHOT     UpdateType = 1
	UpdateType_UPDATE_TYPE_NODE_ADDED   UpdateType = 2
	UpdateType_UPDATE_TYPE_NODE_UPDATED UpdateType = 3
	UpdateType_UPDATE_TYPE_NODE_REMOVED UpdateType = 4
	UpdateType_UPDATE_TYPE_EDGE_ADDED   UpdateType = 5
	UpdateType_UPDATE_TYPE_EDGE_UPDATED UpdateType = 6
	UpdateType_UPDATE_TYPE_EDGE_REMOVED UpdateType = 7
)

// Enum value maps for UpdateType.
var (
	UpdateType_name = map[int32]string{
		0: "UPDATE_TYPE_UNSPECIFIED",
		1: "UPDATE_TYPE_SNAPSHOT",
		2: "UPDATE_TYPE_NODE_ADDED",
		3: "UPDATE_TYPE_NODE_UPDATED",
		4: "UPDATE_TYPE_NODE_REMOVED",
		5: "UPDATE_TYPE_EDGE_ADDED",
		6: "UPDATE_TYPE_EDGE_UPDATED",
		7: "UPDATE_TYPE_EDGE_REMOVED",
	}
	UpdateType_value = map[string]int32{
		"UPDATE_TYPE_UNSPECIFIED":  0,
		"UPDATE_TYPE_SNAPSHOT":     1,
		"UPDATE_TYPE_NODE_ADDED":   2,
		"UPDATE_TYPE_NODE_UPDATED": 3,
		"UPDATE_TYPE_NODE_REMOVED": 4,
		"UPDATE_TYPE_EDGE_ADDED":   5,
		"UPDATE_TYPE_EDGE_UPDATED": 6,
		"UPDATE_TYPE_EDGE_REMOVED": 7,
	}
)

func (x UpdateType) Enum() *UpdateType {
	p := new(UpdateType)
	*p = x
	return p
}

func (x UpdateType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UpdateType) Descriptor() protoreflect.EnumDescriptor {
	return file_runtime_v1_topology_proto_enumTypes[5].Descriptor()
}

func (UpdateType) Type() protoreflect.EnumType {
	return &file_runtime_v1_topology_proto_enumTypes[5]
}

func (x UpdateType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UpdateType.Descriptor instead.
func (UpdateType) EnumDescriptor() ([]byte, []int) {
	return file_runtime_v1_topology_proto_rawDescGZIP(), []int{5}
}

// ActivityType represents the kind of activity event.
type ActivityType int32

const (
	ActivityType_ACTIVITY_TYPE_UNSPECIFIED       ActivityType = 0
	ActivityType_ACTIVITY_TYPE_REQUEST_SENT      ActivityType = 1
	ActivityType_ACTIVITY_TYPE_RESPONSE_RECEIVED ActivityType = 2
	ActivityType_ACTIVITY_TYPE_ERROR             ActivityType = 3
)

// Enum value maps for ActivityType.
var (
	ActivityType_name = map[int32]string{
		0: "ACTIVITY_TYPE_UNSPECIFIED",
		1: "ACTIVITY_TYPE_REQUEST_SENT",
		2: "ACTIVITY_TYPE_RESPONSE_RECEIVED",
		3: "ACTIVITY_TYPE_ERROR",
	}
	ActivityType_value = map[string]int32{
		"ACTIVITY_TYPE_UNSPECIFIED":       0,
		"ACTIVITY_TYPE_REQUEST_SENT":      1,
		"ACTIVITY_TYPE_RESPONSE_RECEIVED": 2,
		"ACTIVITY_TYPE_ERROR":             3,
	}
)

func (x ActivityType) Enum() *ActivityType {
	p := new(ActivityType)
	*p = x
	return p
}

func (x ActivityType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ActivityType) Descriptor() protoreflect.EnumDescriptor {
	return file_runtime_v1_topology_proto_enumTypes[6].Descriptor()
}

func (ActivityType) Type() protoreflect.EnumType {
	return &file_runtime_v1_topology_proto_enumTypes[6]
}

func (x ActivityType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ActivityType.Descriptor instead.
func (ActivityType) EnumDescriptor() ([]byte, []int) {
	return file_runtime_v1_topology_proto_rawDescGZIP(), []int{6}
}

// ServiceMetadata provides structured, optional metadata.
type ServiceMetadata struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Region           *string                `protobuf:"bytes,1,opt,name=region,proto3,oneof" json:"region,omitempty"`
	Environment      *string                `protobuf:"bytes,2,opt,name=environment,proto3,oneof" json:"environment,omitempty"`
	Team             *string                `protobuf:"bytes,3,opt,name=team,proto3,oneof" json:"team,omitempty"`
	VersionHash      *string                `protobuf:"bytes,4,opt,name=version_hash,json=versionHash,proto3,oneof" json:"version_hash,omitempty"`
	ServiceInterface *string                `protobuf:"bytes,5,opt,name=service_interface,json=serviceInterface,proto3,oneof" json:"service_interface,omitempty"`
	ServiceRole      *string                `protobuf:"bytes,6,opt,name=service_role,json=serviceRole,proto3,oneof" json:"service_role,omitempty"`
	ProgramName      *string                `protobuf:"bytes,7,opt,name=program_name,json=programName,proto3,oneof" json:"program_name,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ServiceMetadata) Reset() {
	*x = ServiceMetadata{}
	mi := &file_runtime_v1_topology_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceMetadata) ProtoMessage() {}

func (x *ServiceMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v1_topology_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceMetadata.ProtoReflect.Descriptor instead.
func (*ServiceMetadata) Descriptor() ([]byte, []int) {
	return file_runtime_v1_topology_proto_rawDescGZIP(), []int{0}
}

func (x *ServiceMetadata) GetRegion() string {
	if x != nil && x.Region != nil {
		return *x.Region
	}
	return ""
}

func (x *ServiceMetadata) GetEnvironment() string {
	if x != nil && x.Environment != nil {
		return *x.Environment
	}
	return ""
}

func (x *ServiceMetadata) GetTeam() string {
	if x != nil && x.Team != nil {
		return *x.Team
	}
	return ""
}

func (x *ServiceMetadata) GetVersionHash() string {
	if x != nil && x.VersionHash != nil {
		return *x.VersionHash
	}
	return ""
}

func (x *ServiceMetadata) GetServiceInterface() string {
	if x != nil && x.ServiceInterface != nil {
		return *x.ServiceInterface
	}
	return ""
}

func (x *ServiceMetadata) GetServiceRole() string {
	if x != nil && x.ServiceRole != nil {
		return *x.ServiceRole
	}
	return ""
}

func (x *ServiceMetadata) GetProgramName() string {
	if x != nil && x.ProgramName != nil {
		return *x.ProgramName
	}
	return ""
}

// ServiceMetrics contains optional runtime metrics.
type ServiceMetrics struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CpuPercent    float64                `protobuf:"fixed64,1,opt,name=cpu_percent,json=cpuPercent,proto3" json:"cpu_percent,omitempty"`
	MemoryBytes   uint64                 `protobuf:"varint,2,opt,name=memory_bytes,json=memoryBytes,proto3" json:"memory_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceMetrics) Reset() {
	*x = ServiceMetrics{}
	mi := &file_runtime_v1_topology_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceMetrics) ProtoMessage() {}

func (x *ServiceMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v1_topology_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceMetrics.ProtoReflect.Descriptor instead.
func (*ServiceMetrics) Descriptor() ([]byte, []int) {
	return file_runtime_v1_topology_proto_rawDescGZIP(), []int{1}
}

func (x *ServiceMetrics) GetCpuPercent() float64 {
	if x != nil {
		return x.CpuPercent
	}
	return 0
}

func (x *ServiceMetrics) GetMemoryBytes() uint64 {
	if x != nil {
		return x.MemoryBytes
	}
	return 0
}

// ApplicationHealth provides application-level health details.
type ApplicationHealth struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         HealthState            `protobuf:"varint,1,opt,name=state,proto3,enum=runtime.v1.HealthState" json:"state,omitempty"`
	Message       *string                `protobuf:"bytes,2,opt,name=message,proto3,oneof" json:"message,omitempty"`
	ErrorCount    *int32                 `protobuf:"varint,3,opt,name=error_count,json=errorCount,proto3,oneof" json:"error_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplicationHealth) Reset() {
	*x = ApplicationHealth{}
	mi := &file_runtime_v1_topology_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplicationHealth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplicationHealth) ProtoMessage() {}

func (x *ApplicationHealth) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v1_topology_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplicationHealth.ProtoReflect.Descriptor instead.
func (*ApplicationHealth) Descriptor() ([]byte, []int) {
	return file_runtime_v1_topology_proto_rawDescGZIP(), []int{2}
}

func (x *ApplicationHealth) GetState() HealthState {
	if x != nil {
		return x.State
	}
	return HealthState_HEALTH_STATE_UNKNOWN
}

func (x *ApplicationHealth) GetMessage() string {
	if x != nil && x.Message != nil {
		return *x.Message
	}
	return ""
}

func (x *ApplicationHealth) GetErrorCount() int32 {
	if x != nil && x.ErrorCount != nil {
		return *x.ErrorCount
	}
	return 0
}

// RegisterServiceRequest registers a service and returns a handle.
type RegisterServiceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceName   string                 `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	ServiceType   ServiceType            `protobuf:"varint,2,opt,name=service_type,json=serviceType,proto3,enum=runtime.v1.ServiceType" json:"service_type,omitempty"`
	Language      ServiceLanguage        `protobuf:"varint,3,opt,name=language,proto3,enum=runtime.v1.ServiceLanguage" json:"language,omitempty"`
	Version       *string                `protobuf:"bytes,4,opt,name=version,proto3,oneof" json:"version,omitempty"`
	Address       *string                `protobuf:"bytes,5,opt,name=address,proto3,oneof" json:"address,omitempty"`
	Host          *string                `protobuf:"bytes,6,opt,name=host,proto3,oneof" json:"host,omitempty"`
	Metadata      *ServiceMetadata       `protobuf:"bytes,7,opt,name=metadata,proto3,oneof" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterServiceRequest) Reset() {
	*x = RegisterServiceRequest{}
	mi := &file_runtime_v1_topology_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterServiceRequest) ProtoMessage() {}

func (x *RegisterServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v1_topology_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterServiceRequest.ProtoReflect.Descriptor instead.
func (*RegisterServiceRequest) Descriptor() ([]byte, []int) {
	return file_runtime_v1_topology_proto_rawDescGZIP(), []int{3}
}

func (x *RegisterServiceRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *RegisterServiceRequest) GetServiceType() ServiceType {
	if x != nil {
		return x.ServiceType
	}
	return ServiceType_SERVICE_TYPE_UNSPECIFIED
}

func (x *RegisterServiceRequest) GetLanguage() ServiceLanguage {
	if x != nil {
		return x.Language
	}
	return ServiceLanguage_SERVICE_LANGUAGE_UNSPECIFIED
}

func (x *RegisterServiceRequest) GetVersion() string {
	if x != nil && x.Version != nil {
		return *x.Version
	}
	return ""
}

func (x *RegisterServiceRequest) GetAddress() string {
	if x != nil && x.Address != nil {
		return *x.Address
	}
	return ""
}

func (x *RegisterServiceRequest) GetHost() string {
	if x != nil && x.Host != nil {
		return *x.Host
	}
	return ""
}

func (x *RegisterServiceRequest) GetMetadata() *ServiceMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// ServiceHandle is returned after registration.
type ServiceHandle struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	ServiceId           string                 `protobuf:"bytes,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	HeartbeatIntervalMs int32                  `protobuf:"varint,2,opt,name=heartbeat_interval_ms,json=heartbeatIntervalMs,proto3" json:"heartbeat_interval_ms,omitempty"`
	TimeoutMultiplier   int32                  `protobuf:"varint,3,opt,name=timeout_multiplier,json=timeoutMultiplier,proto3" json:"timeout_multiplier,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ServiceHandle) Reset() {
	*x = ServiceHandle{}
	mi := &file_runtime_v1_topology_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceHandle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceHandle) ProtoMessage() {}

func (x *ServiceHandle) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v1_topology_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceHandle.ProtoReflect.Descriptor instead.
func (*ServiceHandle) Descriptor() ([]byte, []int) {
	return file_runtime_v1_topology_proto_rawDescGZIP(), []int{4}
}

func (x *ServiceHandle) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *ServiceHandle) GetHeartbeatIntervalMs() int32 {
	if x != nil {
		return x.HeartbeatIntervalMs
	}
	return 0
}

func (x *ServiceHandle) GetTimeoutMultiplier() int32 {
	if x != nil {
		return x.TimeoutMultiplier
	}
	return 0
}

// HeartbeatRequest keeps a service alive.
type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceId     string                 `protobuf:"bytes,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	Sequence      int64                  `protobuf:"varint,2,opt,name=sequence,proto3" json:"sequence,omitempty"`
	Metrics       *ServiceMetrics        `protobuf:"bytes,3,opt,name=metrics,proto3,oneof" json:"metrics,omitempty"`
	Health        *ApplicationHealth     `protobuf:"bytes,4,opt,name=health,proto3,oneof" json:"health,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_runtime_v1_topology_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v1_topology_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_runtime_v1_topology_proto_rawDescGZIP(), []int{5}
}

func (x *HeartbeatRequest) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *HeartbeatRequest) GetSequence() int64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *HeartbeatRequest) GetMetrics() *ServiceMetrics {
	if x != nil {
		return x.Metrics
	}
	return nil
}

func (x *HeartbeatRequest) GetHealth() *ApplicationHealth {
	if x != nil {
		return x.Health
	}
	return nil
}

// HeartbeatResponse acknowledges a heartbeat.
type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sequence      int64                  `protobuf:"varint,1,opt,name=sequence,proto3" json:"sequence,omitempty"`
	Acknowledged  bool                   `protobuf:"varint,2,opt,name=acknowledged,proto3" json:"acknowledged,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_runtime_v1_topology_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v1_topology_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_runtime_v1_topology_proto_rawDescGZIP(), []int{6}
}

func (x *HeartbeatResponse) GetSequence() int64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *HeartbeatResponse) GetAcknowledged() bool {
	if x != nil {
		return x.Acknowledged
	}
	return false
}

// ReportActivityRequest represents an optional activity report.
type ReportActivityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceId     string                 `protobuf:"bytes,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	TargetService string                 `protobuf:"bytes,2,opt,name=target_service,json=targetService,proto3" json:"target_service,omitempty"`
	Type          ActivityType           `protobuf:"varint,3,opt,name=type,proto3,enum=runtime.v1.ActivityType" json:"type,omitempty"`
	TimestampMs   *int64                 `protobuf:"varint,4,opt,name=timestamp_ms,json=timestampMs,proto3,oneof" json:"timestamp_ms,omitempty"`
	LatencyMs     *int32                 `protobuf:"varint,5,opt,name=latency_ms,json=latencyMs,proto3,oneof" json:"latency_ms,omitempty"`
	Method        *string                `protobuf:"bytes,6,opt,name=method,proto3,oneof" json:"method,omitempty"`
	Success       *bool                  `protobuf:"varint,7,opt,name=success,proto3,oneof" json:"success,omitempty"`
	BatchSize     *int32                 `protobuf:"varint,8,opt,name=batch_size,json=batchSize,proto3,oneof" json:"batch_size,omitempty"`
	ErrorMessage  *string                `protobuf:"bytes,9,opt,name=error_message,json=errorMessage,proto3,oneof" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportActivityRequest) Reset() {
	*x = ReportActivityRequest{}
	mi := &file_runtime_v1_topology_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportActivityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportActivityRequest) ProtoMessage() {}

func (x *ReportActivityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v1_topology_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportActivityRequest.ProtoReflect.Descriptor instead.
func (*ReportActivityRequest) Descriptor() ([]byte, []int) {
	return file_runtime_v1_topology_proto_rawDescGZIP(), []int{7}
}

func (x *ReportActivityRequest) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *ReportActivityRequest) GetTargetService() string {
	if x != nil {
		return x.TargetService
	}
	return ""
}

func (x *ReportActivityRequest) GetType() ActivityType {
	if x != nil {
		return x.Type
	}
	return ActivityType_ACTIVITY_TYPE_UNSPECIFIED
}

func (x *ReportActivityRequest) GetTimestampMs() int64 {
	if x != nil && x.TimestampMs != nil {
		return *x.TimestampMs
	}
	return 0
}

func (x *ReportActivityRequest) GetLatencyMs() int32 {
	if x != nil && x.LatencyMs != nil {
		return *x.LatencyMs
	}
	return 0
}

func (x *ReportActivityRequest) GetMethod() string {
	if x != nil && x.Method != nil {
		return *x.Method
	}
	return ""
}

func (x *ReportActivityRequest) GetSuccess() bool {
	if x != nil && x.Success != nil {
		return *x.Success
	}
	return false
}

func (x *ReportActivityRequest) GetBatchSize() int32 {
	if x != nil && x.BatchSize != nil {
		return *x.BatchSize
	}
	return 0
}

func (x *ReportActivityRequest) GetErrorMessage() string {
	if x != nil && x.ErrorMessage != nil {
		return *x.ErrorMessage
	}
	return ""
}

// ReportActivityResponse confirms receipt of activity events.
type ReportActivityResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Acknowledged   bool                   `protobuf:"varint,1,opt,name=acknowledged,proto3" json:"acknowledged,omitempty"`
	AcceptedEvents int64                  `protobuf:"varint,2,opt,name=accepted_events,json=acceptedEvents,proto3" json:"accepted_events,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ReportActivityResponse) Reset() {
	*x = ReportActivityResponse{}
	mi := &file_runtime_v1_topology_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportActivityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportActivityResponse) ProtoMessage() {}

func (x *ReportActivityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v1_topology_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportActivityResponse.ProtoReflect.Descriptor instead.
func (*ReportActivityResponse) Descriptor() ([]byte, []int) {
	return file_runtime_v1_topology_proto_rawDescGZIP(), []int{8}
}

func (x *ReportActivityResponse) GetAcknowledged() bool {
	if x != nil {
		return x.Acknowledged
	}
	return false
}

func (x *ReportActivityResponse) GetAcceptedEvents() int64 {
	if x != nil {
		return x.AcceptedEvents
	}
	return 0
}

// TopologyQuery allows filtering the topology view.
type TopologyQuery struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceNames  []string               `protobuf:"bytes,1,rep,name=service_names,json=serviceNames,proto3" json:"service_names,omitempty"`
	IncludeIdle   bool                   `protobuf:"varint,2,opt,name=include_idle,json=includeIdle,proto3" json:"include_idle,omitempty"`
	IncludeStale  bool                   `protobuf:"varint,3,opt,name=include_stale,json=includeStale,proto3" json:"include_stale,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopologyQuery) Reset() {
	*x = TopologyQuery{}
	mi := &file_runtime_v1_topology_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopologyQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopologyQuery) ProtoMessage() {}

func (x *TopologyQuery) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v1_topology_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopologyQuery.ProtoReflect.Descriptor instead.
func (*TopologyQuery) Descriptor() ([]byte, []int) {
	return file_runtime_v1_topology_proto_rawDescGZIP(), []int{9}
}

func (x *TopologyQuery) GetServiceNames() []string {
	if x != nil {
		return x.ServiceNames
	}
	return nil
}

func (x *TopologyQuery) GetIncludeIdle() bool {
	if x != nil {
		return x.IncludeIdle
	}
	return false
}

func (x *TopologyQuery) GetIncludeStale() bool {
	if x != nil {
		return x.IncludeStale
	}
	return false
}

// RegisterServiceResponse returns the service handle.
type RegisterServiceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Handle        *ServiceHandle         `protobuf:"bytes,1,opt,name=handle,proto3" json:"handle,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterServiceResponse) Reset() {
	*x = RegisterServiceResponse{}
	mi := &file_runtime_v1_topology_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterServiceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterServiceResponse) ProtoMessage() {}

func (x *RegisterServiceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v1_topology_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterServiceResponse.ProtoReflect.Descriptor instead.
func (*RegisterServiceResponse) Descriptor() ([]byte, []int) {
	return file_runtime_v1_topology_proto_rawDescGZIP(), []int{10}
}

func (x *RegisterServiceResponse) GetHandle() *ServiceHandle {
	if x != nil {
		return x.Handle
	}
	return nil
}

// UnregisterServiceRequest removes a service by ID.
type UnregisterServiceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceId     string                 `protobuf:"bytes,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnregisterServiceRequest) Reset() {
	*x = UnregisterServiceRequest{}
	mi := &file_runtime_v1_topology_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnregisterServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnregisterServiceRequest) ProtoMessage() {}

func (x *UnregisterServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v1_topology_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnregisterServiceRequest.ProtoReflect.Descriptor instead.
func (*UnregisterServiceRequest) Descriptor() ([]byte, []int) {
	return file_runtime_v1_topology_proto_rawDescGZIP(), []int{11}
}

func (x *UnregisterServiceRequest) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

// UnregisterServiceResponse confirms a removal.
type UnregisterServiceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Removed       bool                   `protobuf:"varint,1,opt,name=removed,proto3" json:"removed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnregisterServiceResponse) Reset() {
	*x = UnregisterServiceResponse{}
	mi := &file_runtime_v1_topology_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnregisterServiceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnregisterServiceResponse) ProtoMessage() {}

func (x *UnregisterServiceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v1_topology_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnregisterServiceResponse.ProtoReflect.Descriptor instead.
func (*UnregisterServiceResponse) Descriptor() ([]byte, []int) {
	return file_runtime_v1_topology_proto_rawDescGZIP(), []int{12}
}

func (x *UnregisterServiceResponse) GetRemoved() bool {
	if x != nil {
		return x.Removed
	}
	return false
}

// GetTopologyRequest fetches the topology snapshot.
type GetTopologyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         *TopologyQuery         `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTopologyRequest) Reset() {
	*x = GetTopologyRequest{}
	mi := &file_runtime_v1_topology_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTopologyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTopologyRequest) ProtoMessage() {}

func (x *GetTopologyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v1_topology_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTopologyRequest.ProtoReflect.Descriptor instead.
func (*GetTopologyRequest) Descriptor() ([]byte, []int) {
	return file_runtime_v1_topology_proto_rawDescGZIP(), []int{13}
}

func (x *GetTopologyRequest) GetQuery() *TopologyQuery {
	if x != nil {
		return x.Query
	}
	return nil
}

// GetTopologyResponse returns the topology snapshot.
type GetTopologyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Snapshot      *TopologySnapshot      `protobuf:"bytes,1,opt,name=snapshot,proto3" json:"snapshot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTopologyResponse) Reset() {
	*x = GetTopologyResponse{}
	mi := &file_runtime_v1_topology_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTopologyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTopologyResponse) ProtoMessage() {}

func (x *GetTopologyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v1_topology_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTopologyResponse.ProtoReflect.Descriptor instead.
func (*GetTopologyResponse) Descriptor() ([]byte, []int) {
	return file_runtime_v1_topology_proto_rawDescGZIP(), []int{14}
}

func (x *GetTopologyResponse) GetSnapshot() *TopologySnapshot {
	if x != nil {
		return x.Snapshot
	}
	return nil
}

// WatchTopologyRequest streams updates for a query.
type WatchTopologyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         *TopologyQuery         `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchTopologyRequest) Reset() {
	*x = WatchTopologyRequest{}
	mi := &file_runtime_v1_topology_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchTopologyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchTopologyRequest) ProtoMessage() {}

func (x *WatchTopologyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v1_topology_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchTopologyRequest.ProtoReflect.Descriptor instead.
func (*WatchTopologyRequest) Descriptor() ([]byte, []int) {
	return file_runtime_v1_topology_proto_rawDescGZIP(), []int{15}
}

func (x *WatchTopologyRequest) GetQuery() *TopologyQuery {
	if x != nil {
		return x.Query
	}
	return nil
}

// WatchTopologyResponse streams topology updates.
type WatchTopologyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Update        *TopologyUpdate        `protobuf:"bytes,1,opt,name=update,proto3" json:"update,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchTopologyResponse) Reset() {
	*x = WatchTopologyResponse{}
	mi := &file_runtime_v1_topology_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchTopologyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchTopologyResponse) ProtoMessage() {}

func (x *WatchTopologyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v1_topology_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchTopologyResponse.ProtoReflect.Descriptor instead.
func (*WatchTopologyResponse) Descriptor() ([]byte, []int) {
	return file_runtime_v1_topology_proto_rawDescGZIP(), []int{16}
}

func (x *WatchTopologyResponse) GetUpdate() *TopologyUpdate {
	if x != nil {
		return x.Update
	}
	return nil
}

// TopologySnapshot represents the full topology state.
type TopologySnapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nodes         []*ServiceNode         `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	Edges         []*ServiceEdge         `protobuf:"bytes,2,rep,name=edges,proto3" json:"edges,omitempty"`
	TimestampMs   int64                  `protobuf:"varint,3,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopologySnapshot) Reset() {
	*x = TopologySnapshot{}
	mi := &file_runtime_v1_topology_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopologySnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopologySnapshot) ProtoMessage() {}

func (x *TopologySnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v1_topology_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopologySnapshot.ProtoReflect.Descriptor instead.
func (*TopologySnapshot) Descriptor() ([]byte, []int) {
	return file_runtime_v1_topology_proto_rawDescGZIP(), []int{17}
}

func (x *TopologySnapshot) GetNodes() []*ServiceNode {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *TopologySnapshot) GetEdges() []*ServiceEdge {
	if x != nil {
		return x.Edges
	}
	return nil
}

func (x *TopologySnapshot) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

// ServiceNode represents a service in the topology graph.
type ServiceNode struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ServiceId       string                 `protobuf:"bytes,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	ServiceName     string                 `protobuf:"bytes,2,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	ServiceType     ServiceType            `protobuf:"varint,3,opt,name=service_type,json=serviceType,proto3,enum=runtime.v1.ServiceType" json:"service_type,omitempty"`
	Language        ServiceLanguage        `protobuf:"varint,4,opt,name=language,proto3,enum=runtime.v1.ServiceLanguage" json:"language,omitempty"`
	Version         *string                `protobuf:"bytes,5,opt,name=version,proto3,oneof" json:"version,omitempty"`
	Address         *string                `protobuf:"bytes,6,opt,name=address,proto3,oneof" json:"address,omitempty"`
	Host            *string                `protobuf:"bytes,7,opt,name=host,proto3,oneof" json:"host,omitempty"`
	Metadata        *ServiceMetadata       `protobuf:"bytes,8,opt,name=metadata,proto3,oneof" json:"metadata,omitempty"`
	State           ServiceState           `protobuf:"varint,9,opt,name=state,proto3,enum=runtime.v1.ServiceState" json:"state,omitempty"`
	LastHeartbeatMs int64                  `protobuf:"varint,10,opt,name=last_heartbeat_ms,json=lastHeartbeatMs,proto3" json:"last_heartbeat_ms,omitempty"`
	LastActivityMs  int64                  `protobuf:"varint,11,opt,name=last_activity_ms,json=lastActivityMs,proto3" json:"last_activity_ms,omitempty"`
	Health          HealthState            `protobuf:"varint,12,opt,name=health,proto3,enum=runtime.v1.HealthState" json:"health,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ServiceNode) Reset() {
	*x = ServiceNode{}
	mi := &file_runtime_v1_topology_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceNode) ProtoMessage() {}

func (x *ServiceNode) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v1_topology_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceNode.ProtoReflect.Descriptor instead.
func (*ServiceNode) Descriptor() ([]byte, []int) {
	return file_runtime_v1_topology_proto_rawDescGZIP(), []int{18}
}

func (x *ServiceNode) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *ServiceNode) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *ServiceNode) GetServiceType() ServiceType {
	if x != nil {
		return x.ServiceType
	}
	return ServiceType_SERVICE_TYPE_UNSPECIFIED
}

func (x *ServiceNode) GetLanguage() ServiceLanguage {
	if x != nil {
		return x.Language
	}
	return ServiceLanguage_SERVICE_LANGUAGE_UNSPECIFIED
}

func (x *ServiceNode) GetVersion() string {
	if x != nil && x.Version != nil {
		return *x.Version
	}
	return ""
}

func (x *ServiceNode) GetAddress() string {
	if x != nil && x.Address != nil {
		return *x.Address
	}
	return ""
}

func (x *ServiceNode) GetHost() string {
	if x != nil && x.Host != nil {
		return *x.Host
	}
	return ""
}

func (x *ServiceNode) GetMetadata() *ServiceMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *ServiceNode) GetState() ServiceState {
	if x != nil {
		return x.State
	}
	return ServiceState_SERVICE_STATE_UNSPECIFIED
}

func (x *ServiceNode) GetLastHeartbeatMs() int64 {
	if x != nil {
		return x.LastHeartbeatMs
	}
	return 0
}

func (x *ServiceNode) GetLastActivityMs() int64 {
	if x != nil {
		return x.LastActivityMs
	}
	return 0
}

func (x *ServiceNode) GetHealth() HealthState {
	if x != nil {
		return x.Health
	}
	return HealthState_HEALTH_STATE_UNKNOWN
}

// ServiceEdge represents a connection between services.
type ServiceEdge struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SourceServiceId string                 `protobuf:"bytes,1,opt,name=source_service_id,json=sourceServiceId,proto3" json:"source_service_id,omitempty"`
	TargetService   string                 `protobuf:"bytes,2,opt,name=target_service,json=targetService,proto3" json:"target_service,omitempty"`
	State           ConnectionState        `protobuf:"varint,3,opt,name=state,proto3,enum=runtime.v1.ConnectionState" json:"state,omitempty"`
	LastActivityMs  int64                  `protobuf:"varint,4,opt,name=last_activity_ms,json=lastActivityMs,proto3" json:"last_activity_ms,omitempty"`
	TotalRequests   uint64                 `protobuf:"varint,5,opt,name=total_requests,json=totalRequests,proto3" json:"total_requests,omitempty"`
	TotalErrors     uint64                 `protobuf:"varint,6,opt,name=total_errors,json=totalErrors,proto3" json:"total_errors,omitempty"`
	AvgLatencyMs    float64                `protobuf:"fixed64,7,opt,name=avg_latency_ms,json=avgLatencyMs,proto3" json:"avg_latency_ms,omitempty"`
	Rps             float64                `protobuf:"fixed64,8,opt,name=rps,proto3" json:"rps,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ServiceEdge) Reset() {
	*x = ServiceEdge{}
	mi := &file_runtime_v1_topology_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceEdge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceEdge) ProtoMessage() {}

func (x *ServiceEdge) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v1_topology_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceEdge.ProtoReflect.Descriptor instead.
func (*ServiceEdge) Descriptor() ([]byte, []int) {
	return file_runtime_v1_topology_proto_rawDescGZIP(), []int{19}
}

func (x *ServiceEdge) GetSourceServiceId() string {
	if x != nil {
		return x.SourceServiceId
	}
	return ""
}

func (x *ServiceEdge) GetTargetService() string {
	if x != nil {
		return x.TargetService
	}
	return ""
}

func (x *ServiceEdge) GetState() ConnectionState {
	if x != nil {
		return x.State
	}
	return ConnectionState_CONNECTION_STATE_UNSPECIFIED
}

func (x *ServiceEdge) GetLastActivityMs() int64 {
	if x != nil {
		return x.LastActivityMs
	}
	return 0
}

func (x *ServiceEdge) GetTotalRequests() uint64 {
	if x != nil {
		return x.TotalRequests
	}
	return 0
}

func (x *ServiceEdge) GetTotalErrors() uint64 {
	if x != nil {
		return x.TotalErrors
	}
	return 0
}

func (x *ServiceEdge) GetAvgLatencyMs() float64 {
	if x != nil {
		return x.AvgLatencyMs
	}
	return 0
}

func (x *ServiceEdge) GetRps() float64 {
	if x != nil {
		return x.Rps
	}
	return 0
}

// TopologyUpdate represents a change to the topology graph.
type TopologyUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          UpdateType             `protobuf:"varint,1,opt,name=type,proto3,enum=runtime.v1.UpdateType" json:"type,omitempty"`
	Node          *ServiceNode           `protobuf:"bytes,2,opt,name=node,proto3,oneof" json:"node,omitempty"`
	Edge          *ServiceEdge           `protobuf:"bytes,3,opt,name=edge,proto3,oneof" json:"edge,omitempty"`
	Snapshot      *TopologySnapshot      `protobuf:"bytes,4,opt,name=snapshot,proto3,oneof" json:"snapshot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopologyUpdate) Reset() {
	*x = TopologyUpdate{}
	mi := &file_runtime_v1_topology_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopologyUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopologyUpdate) ProtoMessage() {}

func (x *TopologyUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v1_topology_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopologyUpdate.ProtoReflect.Descriptor instead.
func (*TopologyUpdate) Descriptor() ([]byte, []int) {
	return file_runtime_v1_topology_proto_rawDescGZIP(), []int{20}
}

func (x *TopologyUpdate) GetType() UpdateType {
	if x != nil {
		return x.Type
	}
	return UpdateType_UPDATE_TYPE_UNSPECIFIED
}

func (x *TopologyUpdate) GetNode() *ServiceNode {
	if x != nil {
		return x.Node
	}
	return nil
}

func (x *TopologyUpdate) GetEdge() *ServiceEdge {
	if x != nil {
		return x.Edge
	}
	return nil
}

func (x *TopologyUpdate) GetSnapshot() *TopologySnapshot {
	if x != nil {
		return x.Snapshot
	}
	return nil
}

var File_runtime_v1_topology_proto protoreflect.FileDescriptor

const file_runtime_v1_topology_proto_rawDesc = "" +
	"\n" +
	"\x19runtime/v1/topology.proto\x12\n" +
	"runtime.v1\"\x85\x03\n" +
	"\x0fServiceMetadata\x12\x1b\n" +
	"\x06region\x18\x01 \x01(\tH\x00R\x06region\x88\x01\x01\x12%\n" +
	"\venvironment\x18\x02 \x01(\tH\x01R\venvironment\x88\x01\x01\x12\x17\n" +
	"\x04team\x18\x03 \x01(\tH\x02R\x04team\x88\x01\x01\x12&\n" +
	"\fversion_hash\x18\x04 \x01(\tH\x03R\vversionHash\x88\x01\x01\x120\n" +
	"\x11service_interface\x18\x05 \x01(\tH\x04R\x10serviceInterface\x88\x01\x01\x12&\n" +
	"\fservice_role\x18\x06 \x01(\tH\x05R\vserviceRole\x88\x01\x01\x12&\n" +
	"\fprogram_name\x18\a \x01(\tH\x06R\vprogramName\x88\x01\x01B\t\n" +
	"\a_regionB\x0e\n" +
	"\f_environmentB\a\n" +
	"\x05_teamB\x0f\n" +
	"\r_version_hashB\x14\n" +
	"\x12_service_interfaceB\x0f\n" +
	"\r_service_roleB\x0f\n" +
	"\r_program_name\"T\n" +
	"\x0eServiceMetrics\x12\x1f\n" +
	"\vcpu_percent\x18\x01 \x01(\x01R\n" +
	"cpuPercent\x12!\n" +
	"\fmemory_bytes\x18\x02 \x01(\x04R\vmemoryBytes\"\xa3\x01\n" +
	"\x11ApplicationHealth\x12-\n" +
	"\x05state\x18\x01 \x01(\x0e2\x17.runtime.v1.HealthStateR\x05state\x12\x1d\n" +
	"\amessage\x18\x02 \x01(\tH\x00R\amessage\x88\x01\x01\x12$\n" +
	"\verror_count\x18\x03 \x01(\x05H\x01R\n" +
	"errorCount\x88\x01\x01B\n" +
	"\n" +
	"\b_messageB\x0e\n" +
	"\f_error_count\"\xf3\x02\n" +
	"\x16RegisterServiceRequest\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\x12:\n" +
	"\fservice_type\x18\x02 \x01(\x0e2\x17.runtime.v1.ServiceTypeR\vserviceType\x127\n" +
	"\blanguage\x18\x03 \x01(\x0e2\x1b.runtime.v1.ServiceLanguageR\blanguage\x12\x1d\n" +
	"\aversion\x18\x04 \x01(\tH\x00R\aversion\x88\x01\x01\x12\x1d\n" +
	"\aaddress\x18\x05 \x01(\tH\x01R\aaddress\x88\x01\x01\x12\x17\n" +
	"\x04host\x18\x06 \x01(\tH\x02R\x04host\x88\x01\x01\x12<\n" +
	"\bmetadata\x18\a \x01(\v2\x1b.runtime.v1.ServiceMetadataH\x03R\bmetadata\x88\x01\x01B\n" +
	"\n" +
	"\b_versionB\n" +
	"\n" +
	"\b_addressB\a\n" +
	"\x05_hostB\v\n" +
	"\t_metadata\"\x91\x01\n" +
	"\rServiceHandle\x12\x1d\n" +
	"\n" +
	"service_id\x18\x01 \x01(\tR\tserviceId\x122\n" +
	"\x15heartbeat_interval_ms\x18\x02 \x01(\x05R\x13heartbeatIntervalMs\x12-\n" +
	"\x12timeout_multiplier\x18\x03 \x01(\x05R\x11timeoutMultiplier\"\xdb\x01\n" +
	"\x10HeartbeatRequest\x12\x1d\n" +
	"\n" +
	"service_id\x18\x01 \x01(\tR\tserviceId\x12\x1a\n" +
	"\bsequence\x18\x02 \x01(\x03R\bsequence\x129\n" +
	"\ametrics\x18\x03 \x01(\v2\x1a.runtime.v1.ServiceMetricsH\x00R\ametrics\x88\x01\x01\x12:\n" +
	"\x06health\x18\x04 \x01(\v2\x1d.runtime.v1.ApplicationHealthH\x01R\x06health\x88\x01\x01B\n" +
	"\n" +
	"\b_metricsB\t\n" +
	"\a_health\"S\n" +
	"\x11HeartbeatResponse\x12\x1a\n" +
	"\bsequence\x18\x01 \x01(\x03R\bsequence\x12\"\n" +
	"\facknowledged\x18\x02 \x01(\bR\facknowledged\"\xb9\x03\n" +
	"\x15ReportActivityRequest\x12\x1d\n" +
	"\n" +
	"service_id\x18\x01 \x01(\tR\tserviceId\x12%\n" +
	"\x0etarget_service\x18\x02 \x01(\tR\rtargetService\x12,\n" +
	"\x04type\x18\x03 \x01(\x0e2\x18.runtime.v1.ActivityTypeR\x04type\x12&\n" +
	"\ftimestamp_ms\x18\x04 \x01(\x03H\x00R\vtimestampMs\x88\x01\x01\x12\"\n" +
	"\n" +
	"latency_ms\x18\x05 \x01(\x05H\x01R\tlatencyMs\x88\x01\x01\x12\x1b\n" +
	"\x06method\x18\x06 \x01(\tH\x02R\x06method\x88\x01\x01\x12\x1d\n" +
	"\asuccess\x18\a \x01(\bH\x03R\asuccess\x88\x01\x01\x12\"\n" +
	"\n" +
	"batch_size\x18\b \x01(\x05H\x04R\tbatchSize\x88\x01\x01\x12(\n" +
	"\rerror_message\x18\t \x01(\tH\x05R\ferrorMessage\x88\x01\x01B\x0f\n" +
	"\r_timestamp_msB\r\n" +
	"\v_latency_msB\t\n" +
	"\a_methodB\n" +
	"\n" +
	"\b_successB\r\n" +
	"\v_batch_sizeB\x10\n" +
	"\x0e_error_message\"e\n" +
	"\x16ReportActivityResponse\x12\"\n" +
	"\facknowledged\x18\x01 \x01(\bR\facknowledged\x12'\n" +
	"\x0faccepted_events\x18\x02 \x01(\x03R\x0eacceptedEvents\"|\n" +
	"\rTopologyQuery\x12#\n" +
	"\rservice_names\x18\x01 \x03(\tR\fserviceNames\x12!\n" +
	"\finclude_idle\x18\x02 \x01(\bR\vincludeIdle\x12#\n" +
	"\rinclude_stale\x18\x03 \x01(\bR\fincludeStale\"L\n" +
	"\x17RegisterServiceResponse\x121\n" +
	"\x06handle\x18\x01 \x01(\v2\x19.runtime.v1.ServiceHandleR\x06handle\"9\n" +
	"\x18UnregisterServiceRequest\x12\x1d\n" +
	"\n" +
	"service_id\x18\x01 \x01(\tR\tserviceId\"5\n" +
	"\x19UnregisterServiceResponse\x12\x18\n" +
	"\aremoved\x18\x01 \x01(\bR\aremoved\"E\n" +
	"\x12GetTopologyRequest\x12/\n" +
	"\x05query\x18\x01 \x01(\v2\x19.runtime.v1.TopologyQueryR\x05query\"O\n" +
	"\x13GetTopologyResponse\x128\n" +
	"\bsnapshot\x18\x01 \x01(\v2\x1c.runtime.v1.TopologySnapshotR\bsnapshot\"G\n" +
	"\x14WatchTopologyRequest\x12/\n" +
	"\x05query\x18\x01 \x01(\v2\x19.runtime.v1.TopologyQueryR\x05query\"K\n" +
	"\x15WatchTopologyResponse\x122\n" +
	"\x06update\x18\x01 \x01(\v2\x1a.runtime.v1.TopologyUpdateR\x06update\"\x93\x01\n" +
	"\x10TopologySnapshot\x12-\n" +
	"\x05nodes\x18\x01 \x03(\v2\x17.runtime.v1.ServiceNodeR\x05nodes\x12-\n" +
	"\x05edges\x18\x02 \x03(\v2\x17.runtime.v1.ServiceEdgeR\x05edges\x12!\n" +
	"\ftimestamp_ms\x18\x03 \x01(\x03R\vtimestampMs\"\xbe\x04\n" +
	"\vServiceNode\x12\x1d\n" +
	"\n" +
	"service_id\x18\x01 \x01(\tR\tserviceId\x12!\n" +
	"\fservice_name\x18\x02 \x01(\tR\vserviceName\x12:\n" +
	"\fservice_type\x18\x03 \x01(\x0e2\x17.runtime.v1.ServiceTypeR\vserviceType\x127\n" +
	"\blanguage\x18\x04 \x01(\x0e2\x1b.runtime.v1.ServiceLanguageR\blanguage\x12\x1d\n" +
	"\aversion\x18\x05 \x01(\tH\x00R\aversion\x88\x01\x01\x12\x1d\n" +
	"\aaddress\x18\x06 \x01(\tH\x01R\aaddress\x88\x01\x01\x12\x17\n" +
	"\x04host\x18\a \x01(\tH\x02R\x04host\x88\x01\x01\x12<\n" +
	"\bmetadata\x18\b \x01(\v2\x1b.runtime.v1.ServiceMetadataH\x03R\bmetadata\x88\x01\x01\x12.\n" +
	"\x05state\x18\t \x01(\x0e2\x18.runtime.v1.ServiceStateR\x05state\x12*\n" +
	"\x11last_heartbeat_ms\x18\n" +
	" \x01(\x03R\x0flastHeartbeatMs\x12(\n" +
	"\x10last_activity_ms\x18\v \x01(\x03R\x0elastActivityMs\x12/\n" +
	"\x06health\x18\f \x01(\x0e2\x17.runtime.v1.HealthStateR\x06healthB\n" +
	"\n" +
	"\b_versionB\n" +
	"\n" +
	"\b_addressB\a\n" +
	"\x05_hostB\v\n" +
	"\t_metadata\"\xbf\x02\n" +
	"\vServiceEdge\x12*\n" +
	"\x11source_service_id\x18\x01 \x01(\tR\x0fsourceServiceId\x12%\n" +
	"\x0etarget_service\x18\x02 \x01(\tR\rtargetService\x121\n" +
	"\x05state\x18\x03 \x01(\x0e2\x1b.runtime.v1.ConnectionStateR\x05state\x12(\n" +
	"\x10last_activity_ms\x18\x04 \x01(\x03R\x0elastActivityMs\x12%\n" +
	"\x0etotal_requests\x18\x05 \x01(\x04R\rtotalRequests\x12!\n" +
	"\ftotal_errors\x18\x06 \x01(\x04R\vtotalErrors\x12$\n" +
	"\x0eavg_latency_ms\x18\a \x01(\x01R\favgLatencyMs\x12\x10\n" +
	"\x03rps\x18\b \x01(\x01R\x03rps\"\xfe\x01\n" +
	"\x0eTopologyUpdate\x12*\n" +
	"\x04type\x18\x01 \x01(\x0e2\x16.runtime.v1.UpdateTypeR\x04type\x120\n" +
	"\x04node\x18\x02 \x01(\v2\x17.runtime.v1.ServiceNodeH\x00R\x04node\x88\x01\x01\x120\n" +
	"\x04edge\x18\x03 \x01(\v2\x17.runtime.v1.ServiceEdgeH\x01R\x04edge\x88\x01\x01\x12=\n" +
	"\bsnapshot\x18\x04 \x01(\v2\x1c.runtime.v1.TopologySnapshotH\x02R\bsnapshot\x88\x01\x01B\a\n" +
	"\x05_nodeB\a\n" +
	"\x05_edgeB\v\n" +
	"\t_snapshot*v\n" +
	"\vServiceType\x12\x1c\n" +
	"\x18SERVICE_TYPE_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13SERVICE_TYPE_SERVER\x10\x01\x12\x17\n" +
	"\x13SERVICE_TYPE_CLIENT\x10\x02\x12\x17\n" +
	"\x13SERVICE_TYPE_HYBRID\x10\x03*\xf7\x01\n" +
	"\x0fServiceLanguage\x12 \n" +
	"\x1cSERVICE_LANGUAGE_UNSPECIFIED\x10\x00\x12\x1f\n" +
	"\x1bSERVICE_LANGUAGE_TYPESCRIPT\x10\x01\x12\x19\n" +
	"\x15SERVICE_LANGUAGE_RUST\x10\x02\x12\x18\n" +
	"\x14SERVICE_LANGUAGE_CPP\x10\x03\x12\x17\n" +
	"\x13SERVICE_LANGUAGE_GO\x10\x04\x12\x1b\n" +
	"\x17SERVICE_LANGUAGE_PYTHON\x10\x05\x12\x19\n" +
	"\x15SERVICE_LANGUAGE_JAVA\x10\x06\x12\x1b\n" +
	"\x17SERVICE_LANGUAGE_CSHARP\x10\a*\x93\x01\n" +
	"\vHealthState\x12\x18\n" +
	"\x14HEALTH_STATE_UNKNOWN\x10\x00\x12\x19\n" +
	"\x15HEALTH_STATE_STARTING\x10\x01\x12\x18\n" +
	"\x14HEALTH_STATE_HEALTHY\x10\x02\x12\x19\n" +
	"\x15HEALTH_STATE_DEGRADED\x10\x03\x12\x1a\n" +
	"\x16HEALTH_STATE_UNHEALTHY\x10\x04*\xae\x01\n" +
	"\fServiceState\x12\x1d\n" +
	"\x19SERVICE_STATE_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18SERVICE_STATE_REGISTERED\x10\x01\x12\x16\n" +
	"\x12SERVICE_STATE_IDLE\x10\x02\x12\x18\n" +
	"\x14SERVICE_STATE_ACTIVE\x10\x03\x12\x17\n" +
	"\x13SERVICE_STATE_STALE\x10\x04\x12\x16\n" +
	"\x12SERVICE_STATE_DEAD\x10\x05*\x88\x01\n" +
	"\x0fConnectionState\x12 \n" +
	"\x1cCONNECTION_STATE_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15CONNECTION_STATE_IDLE\x10\x01\x12\x1b\n" +
	"\x17CONNECTION_STATE_ACTIVE\x10\x02\x12\x1b\n" +
	"\x17CONNECTION_STATE_FAILED\x10\x03*\xf3\x01\n" +
	"\n" +
	"UpdateType\x12\x1b\n" +
	"\x17UPDATE_TYPE_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14UPDATE_TYPE_SNAPSHOT\x10\x01\x12\x1a\n" +
	"\x16UPDATE_TYPE_NODE_ADDED\x10\x02\x12\x1c\n" +
	"\x18UPDATE_TYPE_NODE_UPDATED\x10\x03\x12\x1c\n" +
	"\x18UPDATE_TYPE_NODE_REMOVED\x10\x04\x12\x1a\n" +
	"\x16UPDATE_TYPE_EDGE_ADDED\x10\x05\x12\x1c\n" +
	"\x18UPDATE_TYPE_EDGE_UPDATED\x10\x06\x12\x1c\n" +
	"\x18UPDATE_TYPE_EDGE_REMOVED\x10\a*\x8b\x01\n" +
	"\fActivityType\x12\x1d\n" +
	"\x19ACTIVITY_TYPE_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aACTIVITY_TYPE_REQUEST_SENT\x10\x01\x12#\n" +
	"\x1fACTIVITY_TYPE_RESPONSE_RECEIVED\x10\x02\x12\x17\n" +
	"\x13ACTIVITY_TYPE_ERROR\x10\x032\xa0\x04\n" +
	"\x0fTopologyService\x12Z\n" +
	"\x0fRegisterService\x12\".runtime.v1.RegisterServiceRequest\x1a#.runtime.v1.RegisterServiceResponse\x12L\n" +
	"\tHeartbeat\x12\x1c.runtime.v1.HeartbeatRequest\x1a\x1d.runtime.v1.HeartbeatResponse(\x010\x01\x12Y\n" +
	"\x0eReportActivity\x12!.runtime.v1.ReportActivityRequest\x1a\".runtime.v1.ReportActivityResponse(\x01\x12`\n" +
	"\x11UnregisterService\x12$.runtime.v1.UnregisterServiceRequest\x1a%.runtime.v1.UnregisterServiceResponse\x12N\n" +
	"\vGetTopology\x12\x1e.runtime.v1.GetTopologyRequest\x1a\x1f.runtime.v1.GetTopologyResponse\x12V\n" +
	"\rWatchTopology\x12 .runtime.v1.WatchTopologyRequest\x1a!.runtime.v1.WatchTopologyResponse0\x01B\fZ\n" +
	"runtime/v1b\x06proto3"

var (
	file_runtime_v1_topology_proto_rawDescOnce sync.Once
	file_runtime_v1_topology_proto_rawDescData []byte
)

func file_runtime_v1_topology_proto_rawDescGZIP() []byte {
	file_runtime_v1_topology_proto_rawDescOnce.Do(func() {
		file_runtime_v1_topology_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_runtime_v1_topology_proto_rawDesc), len(file_runtime_v1_topology_proto_rawDesc)))
	})
	return file_runtime_v1_topology_proto_rawDescData
}

var file_runtime_v1_topology_proto_enumTypes = make([]protoimpl.EnumInfo, 7)
var file_runtime_v1_topology_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_runtime_v1_topology_proto_goTypes = []any{
	(ServiceType)(0),                  // 0: runtime.v1.ServiceType
	(ServiceLanguage)(0),              // 1: runtime.v1.ServiceLanguage
	(HealthState)(0),                  // 2: runtime.v1.HealthState
	(ServiceState)(0),                 // 3: runtime.v1.ServiceState
	(ConnectionState)(0),              // 4: runtime.v1.ConnectionState
	(UpdateType)(0),                   // 5: runtime.v1.UpdateType
	(ActivityType)(0),                 // 6: runtime.v1.ActivityType
	(*ServiceMetadata)(nil),           // 7: runtime.v1.ServiceMetadata
	(*ServiceMetrics)(nil),            // 8: runtime.v1.ServiceMetrics
	(*ApplicationHealth)(nil),         // 9: runtime.v1.ApplicationHealth
	(*RegisterServiceRequest)(nil),    // 10: runtime.v1.RegisterServiceRequest
	(*ServiceHandle)(nil),             // 11: runtime.v1.ServiceHandle
	(*HeartbeatRequest)(nil),          // 12: runtime.v1.HeartbeatRequest
	(*HeartbeatResponse)(nil),         // 13: runtime.v1.HeartbeatResponse
	(*ReportActivityRequest)(nil),     // 14: runtime.v1.ReportActivityRequest
	(*ReportActivityResponse)(nil),    // 15: runtime.v1.ReportActivityResponse
	(*TopologyQuery)(nil),             // 16: runtime.v1.TopologyQuery
	(*RegisterServiceResponse)(nil),   // 17: runtime.v1.RegisterServiceResponse
	(*UnregisterServiceRequest)(nil),  // 18: runtime.v1.UnregisterServiceRequest
	(*UnregisterServiceResponse)(nil), // 19: runtime.v1.UnregisterServiceResponse
	(*GetTopologyRequest)(nil),        // 20: runtime.v1.GetTopologyRequest
	(*GetTopologyResponse)(nil),       // 21: runtime.v1.GetTopologyResponse
	(*WatchTopologyRequest)(nil),      // 22: runtime.v1.WatchTopologyRequest
	(*WatchTopologyResponse)(nil),     // 23: runtime.v1.WatchTopologyResponse
	(*TopologySnapshot)(nil),          // 24: runtime.v1.TopologySnapshot
	(*ServiceNode)(nil),               // 25: runtime.v1.ServiceNode
	(*ServiceEdge)(nil),               // 26: runtime.v1.ServiceEdge
	(*TopologyUpdate)(nil),            // 27: runtime.v1.TopologyUpdate
}
var file_runtime_v1_topology_proto_depIdxs = []int32{
	2,  // 0: runtime.v1.ApplicationHealth.state:type_name -> runtime.v1.HealthState
	0,  // 1: runtime.v1.RegisterServiceRequest.service_type:type_name -> runtime.v1.ServiceType
	1,  // 2: runtime.v1.RegisterServiceRequest.language:type_name -> runtime.v1.ServiceLanguage
	7,  // 3: runtime.v1.RegisterServiceRequest.metadata:type_name -> runtime.v1.ServiceMetadata
	8,  // 4: runtime.v1.HeartbeatRequest.metrics:type_name -> runtime.v1.ServiceMetrics
	9,  // 5: runtime.v1.HeartbeatRequest.health:type_name -> runtime.v1.ApplicationHealth
	6,  // 6: runtime.v1.ReportActivityRequest.type:type_name -> runtime.v1.ActivityType
	11, // 7: runtime.v1.RegisterServiceResponse.handle:type_name -> runtime.v1.ServiceHandle
	16, // 8: runtime.v1.GetTopologyRequest.query:type_name -> runtime.v1.TopologyQuery
	24, // 9: runtime.v1.GetTopologyResponse.snapshot:type_name -> runtime.v1.TopologySnapshot
	16, // 10: runtime.v1.WatchTopologyRequest.query:type_name -> runtime.v1.TopologyQuery
	27, // 11: runtime.v1.WatchTopologyResponse.update:type_name -> runtime.v1.TopologyUpdate
	25, // 12: runtime.v1.TopologySnapshot.nodes:type_name -> runtime.v1.ServiceNode
	26, // 13: runtime.v1.TopologySnapshot.edges:type_name -> runtime.v1.ServiceEdge
	0,  // 14: runtime.v1.ServiceNode.service_type:type_name -> runtime.v1.ServiceType
	1,  // 15: runtime.v1.ServiceNode.language:type_name -> runtime.v1.ServiceLanguage
	7,  // 16: runtime.v1.ServiceNode.metadata:type_name -> runtime.v1.ServiceMetadata
	3,  // 17: runtime.v1.ServiceNode.state:type_name -> runtime.v1.ServiceState
	2,  // 18: runtime.v1.ServiceNode.health:type_name -> runtime.v1.HealthState
	4,  // 19: runtime.v1.ServiceEdge.state:type_name -> runtime.v1.ConnectionState
	5,  // 20: runtime.v1.TopologyUpdate.type:type_name -> runtime.v1.UpdateType
	25, // 21: runtime.v1.TopologyUpdate.node:type_name -> runtime.v1.ServiceNode
	26, // 22: runtime.v1.TopologyUpdate.edge:type_name -> runtime.v1.ServiceEdge
	24, // 23: runtime.v1.TopologyUpdate.snapshot:type_name -> runtime.v1.TopologySnapshot
	10, // 24: runtime.v1.TopologyService.RegisterService:input_type -> runtime.v1.RegisterServiceRequest
	12, // 25: runtime.v1.TopologyService.Heartbeat:input_type -> runtime.v1.HeartbeatRequest
	14, // 26: runtime.v1.TopologyService.ReportActivity:input_type -> runtime.v1.ReportActivityRequest
	18, // 27: runtime.v1.TopologyService.UnregisterService:input_type -> runtime.v1.UnregisterServiceRequest
	20, // 28: runtime.v1.TopologyService.GetTopology:input_type -> runtime.v1.GetTopologyRequest
	22, // 29: runtime.v1.TopologyService.WatchTopology:input_type -> runtime.v1.WatchTopologyRequest
	17, // 30: runtime.v1.TopologyService.RegisterService:output_type -> runtime.v1.RegisterServiceResponse
	13, // 31: runtime.v1.TopologyService.Heartbeat:output_type -> runtime.v1.HeartbeatResponse
	15, // 32: runtime.v1.TopologyService.ReportActivity:output_type -> runtime.v1.ReportActivityResponse
	19, // 33: runtime.v1.TopologyService.UnregisterService:output_type -> runtime.v1.UnregisterServiceResponse
	21, // 34: runtime.v1.TopologyService.GetTopology:output_type -> runtime.v1.GetTopologyResponse
	23, // 35: runtime.v1.TopologyService.WatchTopology:output_type -> runtime.v1.WatchTopologyResponse
	30, // [30:36] is the sub-list for method output_type
	24, // [24:30] is the sub-list for method input_type
	24, // [24:24] is the sub-list for extension type_name
	24, // [24:24] is the sub-list for extension extendee
	0,  // [0:24] is the sub-list for field type_name
}

func init() { file_runtime_v1_topology_proto_init() }
func file_runtime_v1_topology_proto_init() {
	if File_runtime_v1_topology_proto != nil {
		return
	}
	file_runtime_v1_topology_proto_msgTypes[0].OneofWrappers = []any{}
	file_runtime_v1_topology_proto_msgTypes[2].OneofWrappers = []any{}
	file_runtime_v1_topology_proto_msgTypes[3].OneofWrappers = []any{}
	file_runtime_v1_topology_proto_msgTypes[5].OneofWrappers = []any{}
	file_runtime_v1_topology_proto_msgTypes[7].OneofWrappers = []any{}
	file_runtime_v1_topology_proto_msgTypes[18].OneofWrappers = []any{}
	file_runtime_v1_topology_proto_msgTypes[20].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_runtime_v1_topology_proto_rawDesc), len(file_runtime_v1_topology_proto_rawDesc)),
			NumEnums:      7,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_runtime_v1_topology_proto_goTypes,
		DependencyIndexes: file_runtime_v1_topology_proto_depIdxs,
		EnumInfos:         file_runtime_v1_topology_proto_enumTypes,
		MessageInfos:      file_runtime_v1_topology_proto_msgTypes,
	}.Build()
	File_runtime_v1_topology_proto = out.File
	file_runtime_v1_topology_proto_goTypes = nil
	file_runtime_v1_topology_proto_depIdxs = nil
}
