// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             (unknown)
// source: runtime/v1/topology.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TopologyService_RegisterService_FullMethodName   = "/runtime.v1.TopologyService/RegisterService"
	TopologyService_Heartbeat_FullMethodName         = "/runtime.v1.TopologyService/Heartbeat"
	TopologyService_ReportActivity_FullMethodName    = "/runtime.v1.TopologyService/ReportActivity"
	TopologyService_UnregisterService_FullMethodName = "/runtime.v1.TopologyService/UnregisterService"
	TopologyService_GetTopology_FullMethodName       = "/runtime.v1.TopologyService/GetTopology"
	TopologyService_WatchTopology_FullMethodName     = "/runtime.v1.TopologyService/WatchTopology"
)

// TopologyServiceClient is the client API for TopologyService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// TopologyService tracks service liveness and activity.
type TopologyServiceClient interface {
	// Register a service (server or client).
	RegisterService(ctx context.Context, in *RegisterServiceRequest, opts ...grpc.CallOption) (*RegisterServiceResponse, error)
	// Heartbeat keeps a service alive.
	Heartbeat(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[HeartbeatRequest, HeartbeatResponse], error)
	// ReportActivity is optional activity reporting.
	ReportActivity(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[ReportActivityRequest, ReportActivityResponse], error)
	// Unregister a service on graceful shutdown.
	UnregisterService(ctx context.Context, in *UnregisterServiceRequest, opts ...grpc.CallOption) (*UnregisterServiceResponse, error)
	// GetTopology returns the current snapshot.
	GetTopology(ctx context.Context, in *GetTopologyRequest, opts ...grpc.CallOption) (*GetTopologyResponse, error)
	// WatchTopology streams topology updates.
	WatchTopology(ctx context.Context, in *WatchTopologyRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[WatchTopologyResponse], error)
}

type topologyServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTopologyServiceClient(cc grpc.ClientConnInterface) TopologyServiceClient {
	return &topologyServiceClient{cc}
}

func (c *topologyServiceClient) RegisterService(ctx context.Context, in *RegisterServiceRequest, opts ...grpc.CallOption) (*RegisterServiceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterServiceResponse)
	err := c.cc.Invoke(ctx, TopologyService_RegisterService_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *topologyServiceClient) Heartbeat(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[HeartbeatRequest, HeartbeatResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TopologyService_ServiceDesc.Streams[0], TopologyService_Heartbeat_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[HeartbeatRequest, HeartbeatResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TopologyService_HeartbeatClient = grpc.BidiStreamingClient[HeartbeatRequest, HeartbeatResponse]

func (c *topologyServiceClient) ReportActivity(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[ReportActivityRequest, ReportActivityResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TopologyService_ServiceDesc.Streams[1], TopologyService_ReportActivity_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ReportActivityRequest, ReportActivityResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TopologyService_ReportActivityClient = grpc.ClientStreamingClient[ReportActivityRequest, ReportActivityResponse]

func (c *topologyServiceClient) UnregisterService(ctx context.Context, in *UnregisterServiceRequest, opts ...grpc.CallOption) (*UnregisterServiceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnregisterServiceResponse)
	err := c.cc.Invoke(ctx, TopologyService_UnregisterService_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *topologyServiceClient) GetTopology(ctx context.Context, in *GetTopologyRequest, opts ...grpc.CallOption) (*GetTopologyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTopologyResponse)
	err := c.cc.Invoke(ctx, TopologyService_GetTopology_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *topologyServiceClient) WatchTopology(ctx context.Context, in *WatchTopologyRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[WatchTopologyResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TopologyService_ServiceDesc.Streams[2], TopologyService_WatchTopology_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchTopologyRequest, WatchTopologyResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TopologyService_WatchTopologyClient = grpc.ServerStreamingClient[WatchTopologyResponse]

// TopologyServiceServer is the server API for TopologyService service.
// All implementations must embed UnimplementedTopologyServiceServer
// for forward compatibility.
//
// TopologyService tracks service liveness and activity.
type TopologyServiceServer interface {
	// Register a service (server or client).
	RegisterService(context.Context, *RegisterServiceRequest) (*RegisterServiceResponse, error)
	// Heartbeat keeps a service alive.
	Heartbeat(grpc.BidiStreamingServer[HeartbeatRequest, HeartbeatResponse]) error
	// ReportActivity is optional activity reporting.
	ReportActivity(grpc.ClientStreamingServer[ReportActivityRequest, ReportActivityResponse]) error
	// Unregister a service on graceful shutdown.
	UnregisterService(context.Context, *UnregisterServiceRequest) (*UnregisterServiceResponse, error)
	// GetTopology returns the current snapshot.
	GetTopology(context.Context, *GetTopologyRequest) (*GetTopologyResponse, error)
	// WatchTopology streams topology updates.
	WatchTopology(*WatchTopologyRequest, grpc.ServerStreamingServer[WatchTopologyResponse]) error
	mustEmbedUnimplementedTopologyServiceServer()
}

// UnimplementedTopologyServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTopologyServiceServer struct{}

func (UnimplementedTopologyServiceServer) RegisterService(context.Context, *RegisterServiceRequest) (*RegisterServiceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterService not implemented")
}
func (UnimplementedTopologyServiceServer) Heartbeat(grpc.BidiStreamingServer[HeartbeatRequest, HeartbeatResponse]) error {
	return status.Error(codes.Unimplemented, "method Heartbeat not implemented")
}
func (UnimplementedTopologyServiceServer) ReportActivity(grpc.ClientStreamingServer[ReportActivityRequest, ReportActivityResponse]) error {
	return status.Error(codes.Unimplemented, "method ReportActivity not implemented")
}
func (UnimplementedTopologyServiceServer) UnregisterService(context.Context, *UnregisterServiceRequest) (*UnregisterServiceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UnregisterService not implemented")
}
func (UnimplementedTopologyServiceServer) GetTopology(context.Context, *GetTopologyRequest) (*GetTopologyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTopology not implemented")
}
func (UnimplementedTopologyServiceServer) WatchTopology(*WatchTopologyRequest, grpc.ServerStreamingServer[WatchTopologyResponse]) error {
	return status.Error(codes.Unimplemented, "method WatchTopology not implemented")
}
func (UnimplementedTopologyServiceServer) mustEmbedUnimplementedTopologyServiceServer() {}
func (UnimplementedTopologyServiceServer) testEmbeddedByValue()                         {}

// UnsafeTopologyServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TopologyServiceServer will
// result in compilation errors.
type UnsafeTopologyServiceServer interface {
	mustEmbedUnimplementedTopologyServiceServer()
}

func RegisterTopologyServiceServer(s grpc.ServiceRegistrar, srv TopologyServiceServer) {
	// If the following call panics, it indicates UnimplementedTopologyServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TopologyService_ServiceDesc, srv)
}

func _TopologyService_RegisterService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TopologyServiceServer).RegisterService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TopologyService_RegisterService_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TopologyServiceServer).RegisterService(ctx, req.(*RegisterServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TopologyService_Heartbeat_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TopologyServiceServer).Heartbeat(&grpc.GenericServerStream[HeartbeatRequest, HeartbeatResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TopologyService_HeartbeatServer = grpc.BidiStreamingServer[HeartbeatRequest, HeartbeatResponse]

func _TopologyService_ReportActivity_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TopologyServiceServer).ReportActivity(&grpc.GenericServerStream[ReportActivityRequest, ReportActivityResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TopologyService_ReportActivityServer = grpc.ClientStreamingServer[ReportActivityRequest, ReportActivityResponse]

func _TopologyService_UnregisterService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnregisterServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TopologyServiceServer).UnregisterService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TopologyService_UnregisterService_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TopologyServiceServer).UnregisterService(ctx, req.(*UnregisterServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TopologyService_GetTopology_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTopologyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TopologyServiceServer).GetTopology(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TopologyService_GetTopology_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TopologyServiceServer).GetTopology(ctx, req.(*GetTopologyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TopologyService_WatchTopology_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchTopologyRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TopologyServiceServer).WatchTopology(m, &grpc.GenericServerStream[WatchTopologyRequest, WatchTopologyResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TopologyService_WatchTopologyServer = grpc.ServerStreamingServer[WatchTopologyResponse]

// TopologyService_ServiceDesc is the grpc.ServiceDesc for TopologyService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TopologyService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "runtime.v1.TopologyService",
	HandlerType: (*TopologyServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterService",
			Handler:    _TopologyService_RegisterService_Handler,
		},
		{
			MethodName: "UnregisterService",
			Handler:    _TopologyService_UnregisterService_Handler,
		},
		{
			MethodName: "GetTopology",
			Handler:    _TopologyService_GetTopology_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Heartbeat",
			Handler:       _TopologyService_Heartbeat_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "ReportActivity",
			Handler:       _TopologyService_ReportActivity_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "WatchTopology",
			Handler:       _TopologyService_WatchTopology_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "runtime/v1/topology.proto",
}
